VotingSystem/urls.py
from django.contrib import admin
from django.urls import include, path
from polls.views import index, authorization

urlpatterns = [
    path('', index.polls),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', authorization.login, name='login'),
]

polls/urls.py
from django.urls import path
from polls.views import authorization, index, postview, post, add

app_name = 'polls'
urlpatterns = [
    path('', index.polls, name='index'),
    path('logout/', authorization.logout, name='logout'),
    path('register/', authorization.register, name='register'),
    path('page/', index.polls, name="page"),
    path('popular/', index.popular, name="popular"),
    path('popular/page/<int:page_number>/', index.popular, name="popular"),
    path('unpopular/', index.unpopular, name="unpopular"),
    path('unpopular/page/<int:page_number>/', index.unpopular, name="unpopular"),
    path('random/', index.random_poll, name="random"),
    path('page/<int:page_number>/', index.polls, name="page"),
    path('post/<int:postid>/', postview.post, name="post"),
    path('vote/<int:postid>/', postview.vote, name='vote'),
    #path('add/', index.add, name='vote'),
    path('add/', add.PostCreateView.as_view(), name='addpost'),
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=512)
    icon = models.ImageField(upload_to='static/media/post_icon/')
    userId = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    checked = models.BooleanField(blank=False, null=False, default=False)
    createDate = models.DateField(auto_now_add=True, auto_now=False)
    modifiedDate = models.DateField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s (%s)" % (self.id, self.title)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'


class Candidate(models.Model):
    postId = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=64, blank=False, null=False)
    description = models.TextField(max_length=300, blank=True, null=True, default='')
    voteCount = models.IntegerField(blank=False, null=False, default=0)
    photo = models.ImageField(upload_to='static/media/candidate_photo/')

    def __str__(self):
        return "Candidate %s %s" % (self.id, self.name)

    def get_id(self):
        return self.id

    class Meta:
        verbose_name = 'Candidate'
        verbose_name_plural = 'Candidates'


class User_Candidate(models.Model):
    userId = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    candidateId = models.ForeignKey(Candidate, on_delete=models.CASCADE, null=True, blank=True)
    postId = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return "%s - %s" % (self.userId, self.candidateId)

    class Meta:
        unique_together = (('userId', 'candidateId'),)

polls/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Post, Candidate
from django.utils import timezone
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Button


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = ('title','description', 'icon')

    @property
    def helper(self):
        helper = FormHelper()
        helper.form_tag = False # This is crucial.
        helper.layout = Layout(
            Fieldset('Create new post', 'title', 'description','icon'),
        )

        return helper


class CandidateFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(CandidateFormHelper, self).__init__(*args, **kwargs)
        self.form_tag = False
        self.layout = Layout(
            Fieldset("Add new candidate", 'name','description', 'photo',),
        )
        #self.helper = CandidateFormHelper()
        #self.helper[:].wrap(self.layout.fields, wrapper_class="housenumber")

CandidateFormset = inlineformset_factory(
    Post,
    Candidate,
    fields=('name','description', 'photo',),
    extra=2,
    can_delete=True,
)

polls/views/add.py
from django.views.generic import CreateView
from django.http import HttpResponseRedirect
from polls.models import Post, Candidate
from polls.forms import PostForm, CandidateFormHelper, CandidateFormset
from django.contrib.auth.decorators import login_required


class PostCreateView(CreateView):
    form_class = PostForm
    template_name = 'polls/addpost_tmp.html'
    model = Post
    success_url = '/'


    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        candidate_form = CandidateFormset()
        candidate_formhelper = CandidateFormHelper()

        return self.render_to_response(
            self.get_context_data(form=form, candidate_form=candidate_form)
        )

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        candidate_form = CandidateFormset(self.request.POST, request.FILES)

        if (form.is_valid() and candidate_form.is_valid()):
            return self.form_valid(form, candidate_form)

        return self.form_invalid(form, candidate_form)

    def form_valid(self, form, candidate_form):
        """
        Called if all forms are valid. Creates a Author instance along
        with associated books and then redirects to a success page.
        """
        self.object = form.save()
        candidate_form.instance = self.object
        candidate_form.save()

        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, candidate_form):
        """
        Called if whether a form is invalid. Re-renders the context
        data with the data-filled forms and errors.
        """
        return self.render_to_response(
            self.get_context_data(form=form, candidate_form=candidate_form)
        )

    def get_context_data(self, **kwargs):
        """ Add formset and formhelper to the context_data. """
        ctx = super(PostCreateView, self).get_context_data(**kwargs)
        candidate_formhelper = CandidateFormHelper()

        if self.request.POST:
            ctx['form'] = PostForm(self.request.POST, self.request.FILES)
            ctx['candidate_form'] = CandidateFormset(self.request.POST)
            ctx['candidate_formhelper'] = candidate_formhelper
        else:
            ctx['form'] = PostForm()
            ctx['candidate_form'] = CandidateFormset()
            ctx['candidate_formhelper'] = candidate_formhelper

        return ctx

polls/views/authorization.py
from __future__ import print_function
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from polls.forms import RegistrationForm
from django.shortcuts import render_to_response, redirect
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.template.context_processors import csrf



def login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            print(request.POST.get('next', '/'))
            return redirect(request.POST.get('next', '/'))
        else:
            args['login_error'] = "User not found"
            return render_to_response('polls/login.html', args)

    else:
        return render_to_response('polls/login.html', args)

def logout(request):
    auth.logout(request)
    return redirect("/")


def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = RegistrationForm()
    if request.POST:
        newuser_form = RegistrationForm(request.POST)
        if newuser_form.is_valid():
            newuser_form.save()
            newuser = auth.authenticate(username=newuser_form.cleaned_data['username'], password=newuser_form.cleaned_data['password2'])
            auth.login(request, newuser)
            return redirect('/')
        else:
            args['form'] = newuser_form
    return render_to_response('polls/reg_form.html', args)

polls/views/index.py
from __future__ import print_function
from django.shortcuts import render_to_response, render
from polls.models import Post, User_Candidate, Candidate
from django.core.paginator import Paginator, EmptyPage
from django.contrib import auth
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
import random
from django.template.context_processors import csrf
from django.contrib.auth.decorators import login_required




def polls(request, page_number=1):
    template_name = 'polls/poll_summary.html'
    try:
        all_polls = Post.objects.all().order_by('-modifiedDate')
        current_page = Paginator(all_polls, 5)
        return render_to_response(template_name, {'post_list' : current_page.page(page_number), 'username': auth.get_user(request).username, 'link': '/polls/page'})
    except( EmptyPage ):
        return render(request, template_name)

def popular(request, page_number=1):
    template_name = 'polls/poll_summary.html'
    count = User_Candidate.objects.values('postId').annotate(dcount=Count('postId')).order_by('dcount').last()['dcount']
    most_popular_posts_id = User_Candidate.objects.values('postId').annotate(dcount=Count('postId')).filter(dcount=count).values('postId')
    most_popular_posts = Post.objects.filter(pk__in=most_popular_posts_id)
    current_page = Paginator(most_popular_posts, 5)
    return render_to_response(template_name, {'post_list' : current_page.page(page_number), 'username': auth.get_user(request).username, 'link': '/polls/popular/page'})


def unpopular(request, page_number=1):
    template_name = 'polls/poll_summary.html'
    count = User_Candidate.objects.values('postId').annotate(dcount=Count('postId')).order_by('dcount').first()['dcount']
    most_unpopular_posts_id = User_Candidate.objects.values('postId').annotate(dcount=Count('postId')).filter(dcount=count).values('postId')
    most_unpopular_posts = Post.objects.filter(pk__in=most_unpopular_posts_id)
    current_page = Paginator(most_unpopular_posts, 5)
    return render_to_response(template_name, {'post_list' : current_page.page(page_number), 'username': auth.get_user(request).username, 'link': '/polls/popular/page'})


def random_poll(request):
    mypost = random.choice(Post.objects.all())
    candidate_list = Candidate.objects.filter(postId=mypost.id)
    context = {'mypost':mypost,
               'candidate_list': candidate_list ,
               'username': auth.get_user(request).username}
    return render(request, 'polls/post.html', context)

@login_required
def add(request):
    args = {}
    args.update(csrf(request))
    if auth.get_user(request).is_anonymous:
        return render_to_response('polls/login.html', args)
    else:
        return render(request, 'polls/addPost.html', {'username': auth.get_user(request).username})

polls/views/post.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from datetime import timezone
from django.urls import reverse
from polls.models import Post, Candidate
#from polls.forms import AddPostForm


def addPost(request):
    return HttpResponse("s")

polls/views/postview.py
from django.db.models import Count
from django.contrib import auth
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from  polls.models import Candidate, User_Candidate, Post
from django.contrib.auth.decorators import login_required

from django.template.defaulttags import register

@register.filter
def lookup(d, key):
    return d[key]

def post(request, postid):
    mypost = get_object_or_404(Post, pk=postid)
    candidate_votes = {a: 0 for a in Candidate.objects.filter(postId=postid)}
    for c_u in User_Candidate.objects.filter(postId=postid):
        candidate_votes[c_u.candidateId]+=1
    context = {'mypost': mypost,
               'username': auth.get_user(request).username,
               'candidate_votes': candidate_votes, }
    return render(request, 'polls/post.html', context)

@login_required
def vote(request, postid):
    post = get_object_or_404(Post, pk=postid)
    selected_candidate = post.candidate_set.get(pk=request.POST['choice'])
    user_post = User_Candidate.objects.filter(userId=request.user.id).filter(postId=post.id)
    if user_post.count() > 0:
        return render(request, 'polls/message.html', {'message': 'You have already voted', 'post': post.id, })
    user_cand = User_Candidate.objects.create()
    user_cand.postId = post
    user_cand.candidateId = selected_candidate
    user_cand.userId = request.user
    user_cand.save()
    return render(request, 'polls/message.html',
                    {'message': 'Thank you! You vote for  ' + user_cand.candidateId.name, 'post': post.id, })

polls/templates/polls/addPost.html
{% extends 'polls/layout.html' %}

{% block content %}
    <div class="container body-content">
        <form method="post" action='/polls/addpost/'>
            {% csrf_token %}
                <div class="form-group">
                    <label for="postTitle">Input Post Title</label>
                    <input class="form-control" type="text" name="title"  >
                </div>
                <div class="form-group">
                    <label for="postDesc">Input Post Description</label>
                    <textarea class="form-control" rows="5" cols="40" name="description"></textarea>
                </div>
                <div>
                    <label for="icon">Choose post Icon:</label>
                    <input class="form-control-file" type="file" name="icon">
                </div>

                <div class="candidateContainer">
                    <div class="addCandidateFields">
                        <div class="form-group">
                            <label for="candidateName">Input candidate name</label>
                            <input class="form-control" type="text" id="candidateName" name="candidateName">
                        </div>
                        <div class="form-group">
                            <label for="candidateDesc">Input candidate info</label>
                            <textarea class="form-control" rows="7" cols="40" name="candidateDesc"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="candidatePhoto">Choose candidate Photo:</label>
                            <input class="form-control-file" type="file" name="candidatePhoto">
                        </div>
                    </div>
                </div>
                <input class="btn btn-primary" id="addCandidate" type="button" value="Add Candidate...">
                <br><br>
                <input class="btn btn-primary" type="submit" value="Create Post" />
            </form>
    </div>
    <!-- <script src="~/lib/jquery/dist/jquery.js"></script>-->

{% endblock %}

polls/templates/polls/addpost_tmp.html
{% extends 'polls/layout.html' %}

{% block content %}

    {% load crispy_forms_tags %}

    <div class='container'>
        <form method='post' enctype="multipart/form-data" class="candidateContainer">
            {% crispy form %}
            {{ candidate_form.management_form }}
            {{ candidate_form.non_form_errors }}

            {% crispy candidate_form candidate_formhelper %}

            <input type="button" value="Add More" id="add_more" onclick="cloneMore()">

            <input class='btn btn-primary' type='submit' value='Save'>
        </form>
    </div>

{% endblock %}

polls/templates/polls/layout.html
<!DOCTYPE html>
<html lang="en" style="min-height: 100%">
<head>
    <meta charset="UTF-8">
    <title>Polls</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/post_summary_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/socials-style.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'polls/add/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'polls/post-style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom border-light sticky-top p-lg-3">
        <div class="container pr-lg-0">
            <a class="navbar-brand font-weight-bold" href="{% url 'polls:index' %}">POLLS</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <form class="form-inline my-2 my-lg-0 w-100">
                    <input class="form-control mx-lg-auto w-50 bg-transparent text-light" type="search" placeholder="Search poll" aria-label="Searc">
                </form>
                <a class="nav-link btn btn-outline-primary mr-2" href="/polls/add/">New Poll</a>
                {% if username %}
                    <a class="nav-link btn btn-outline-success" href="/polls/logout/">Sign Out ({{ username }})</a>
                {% else %}
                    <a class="nav-link btn btn-outline-success" href="/accounts/login/">Sign In</a>
                {% endif %}
            </div>
        </div>

    </nav>

    <div class="container mw-100" >
        <div class="row">
            <div class="col-2 " >
                <div class="my-3 py-3" style="position: fixed;">
                    <a class="nav-link btn btn-outline-primary my-3" href="/polls/popular/">most popular</a>
                    <a class="nav-link btn btn-outline-primary my-3" href="/polls/unpopular/">most unpopular</a>
                    <a class="nav-link btn btn-outline-primary" href="/polls/random/">random poll</a>
                </div>
            </div>
            <div class="col-8 p-lg-4" >
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-2">

            </div>
        </div>
    </div>
    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="{% static 'polls/add/js/common.js' %}"></script>
    <script src="{% static 'polls/add/lib/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'polls/add/js/common.js' %}"></script>
</body>
</html>

polls/templates/polls/login.html
{% extends 'polls/layout.html' %}

{% block content %}
    <div class="col-7 mx-auto bg-white p-5 border border-info rounded">
    <div>
        <div class="text-right">
            <a href="#" class="fa fa-facebook"></a>
            <a href="#" class="fa fa-google"></a>
            <a href="#" class="fa fa-instagram"></a>
        </div>
    </div>
        <form action="/accounts/login/" method="post" class=" mx-a">

        {% csrf_token %}
        <div class="form-group">
            <label for="username" class="font-weight-bold">Name</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="password" class="font-weight-bold">Password</label>
            <input type="password" name="password" class="form-control" id="password" placeholder="Password">
        </div>
        <p>
        {% if login_error %}
            <label class="text-danger">{{ login_error }}</label>
        {% endif %}
        </p>
        <button type="submit" class="btn btn-primary">Sign In</button>
    </form>
    <div class="my-2">
        <a href="/polls/register/">Register</a>
    </div>
    </div>
{% endblock %}

polls/templates/polls/message.html
{% extends 'polls/layout.html' %}

{% block content %}

    <p>{{ message }}</p><br>
    <div class="my-2">
        <a class="btn btn-primary" href="{% url 'polls:post' post %}">Back to Post preview</a>
    </div>
{% endblock %}

polls/templates/polls/poll_summary.html
{% extends 'polls/layout.html' %}

{% block content %}
    <div class="well">
        {% if post_list %}
            {% for post in post_list %}
                <div class="card m-3 my-3 p-2 leftspace">
                    <div class="card-body">
                        <img class="icon" src="/{{ post.icon }}">
                        <h5 class="card-title"><a href="{% url 'polls:post' post.id %}">{{ post.title }}</a></h5>
                        <p class="card-text">{{ post.description|slice:":150" }}...</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </div>

    <nav aria-label="Page navigation example" class="m-3">
            <ul class="pagination">
                {% if post_list.has_previous %}
                    <li class="page-item"><a class="page-link" href="{{ link }}/{{ post_list.previous_page_number }}/" aria-label="Previous">&laquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="">&laquo;</a></li>
                {% endif %}
                {% for page in post_list.paginator.page_range %}
                    {% if page == post_list.number %}
                        <li class="page-item active"><a class="page-link" href="{{ link }}/({ page }}/">{{ page }}</a></li>
                    {% else %}
                        <li><a class="page-link" href="{{ link }}/{{ page }}/">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if post_list.has_next %}
                    <li class="page-item "><a class="page-link" href="{{ link }}/{{ post_list.next_page_number }}/">&raquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="">&raquo;</a></li>
                {% endif %}
            </ul>

    </nav>
{% endblock %}

polls/templates/polls/post.html
{% extends 'polls/layout.html' %}

{% block content %}
    <div class="post-title">
        <h1>{{ mypost.title }}</h1>
    </div>
    <div class="row">
        <div class="col-md-6 post-image-container">
            <img data-toggle="modal" data-target="#postModal" class="post-image" src="/{{ mypost.icon }}">
             <div id="postModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                </div>
                <div class="modal-body">
                  <img src="/{{ mypost.icon }}" alt="post.photo" class="img-responsive post-image">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 post-description-container">
             <p>{{ mypost.description }}</p>
        </div>
    </div>
    <div class="post-title">
        <h3>Candidates:</h3>
    </div>
<ul>
{% for key, values in candidate_votes.items%}
    <h3>{{ key.name }}</h3>
    <div class="row">
        <div class="col-md-6">
          <img data-toggle="modal" data-target="#myModal{{ key.id }}" class="post-image" src="/{{ key.photo }}" alt="candidate.photo">
            <div id="myModal{{ key.id }}" class="modal fade" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                </div>
                <div class="modal-body">
                  <img src="/{{ key.photo }}" alt="candidate.photo" class="img-responsive post-image">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6">
            <p>{{ key.description }}</p>
            <p>
                {{ values}} votes
            </p>
        </div>
    </div>
{% endfor %}
</ul>
<form action="{% url 'polls:vote' mypost.id %}" method="post">
     {% csrf_token %}
   <p><b>Please vote!!!</b></p>
     {% for candidate in candidate_votes.keys%}
         <div class="form-group">
             <input type="radio" name="choice" id="choice{{ candidate.id }}" value="{{ candidate.id }}" />
             <label for="choice{{ candidate.id }}">{{ candidate.name }}</label><br />
         </div>
     {% endfor %}
    <p><input class="btn btn-primary" type="submit" value="Vote"></p>
  </form>
  <p>Created by {{ mypost.userId.username}}</p>
{% endblock %}

polls/templates/polls/reg_form.html
{% extends 'polls/layout.html' %}

{% block content %}
    <div class="col-10 mx-auto bg-white p-5 border border-info rounded">
    <form class="needs-validation" novalidate method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-6 mb-3">
                <label for="id_username">Username:</label>
                <input type="text" class="form-control" name="username" maxlength="150" autofocus required id="id_username"  placeholder="Username"/>
                <div class="invalid-feedback helptext">
                    Please choose a username. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
                </div>
                <div class="valid-feedback">
                    Looks good!
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <label for="id_email">Email:</label>
                <input type="email" class="form-control" name="email" required id="id_email" placeholder="Email"/>
                <div class="invalid-feedback">
                    Please provide correct email
                </div>
                <div class="valid-feedback">
                    Looks good!
                </div>
            </div>
        </div>

        <div class="form-row">
            <div class="col-md-6 mb-3">
                <label for="id_password1">Password:</label>
                <input class="form-control" type="password" name="password1" required id="id_password1" placeholder="Password"/>
                <div class="invalid-feedback helptext">
                    <ul>
                        <li>Your password can&#39;t be too similar to your other personal information.</li>
                        <li>Your password must contain at least 8 characters.</li>
                        <li>Your password can&#39;t be a commonly used password.</li>
                        <li>Your password can&#39;t be entirely numeric.</li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <label for="id_password2">Password confirmation:</label>
                <input class="form-control" type="password" name="password2" required id="id_password2" placeholder="Confirm password" />
                <div class="invalid-feedback helptext">
                    <span class="helptext">Enter the same password as before, for verification.</span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6 mb-3">
                <label for="id_first_name">First name:</label>
                <input class="form-control" type="text" name="first_name" maxlength="30" id="id_first_name"  placeholder="First name" />
                <div class="valid-feedback">
                    Looks good!
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <label for="id_last_name">Last name:</label>
                <input class="form-control" type="text" name="last_name" maxlength="150" id="id_last_name" placeholder="Last name"/>
                <div class="valid-feedback">
                    Looks good!
                </div>
            </div>
        </div>

        <button class="btn btn-primary" type="submit">Register</button>
    </form>
    </div>

    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function() {
            'use strict';
            window.addEventListener('load', function() {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function(form) {
                    form.addEventListener('submit', function(event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>



{% endblock %}